{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.2.8.jar",
          "url": "recipe-0.2.8.jar",
          "size": 51712,
          "sha512": "d617c847c83aa90efd0c3b154d867c281cbfdd1c0072001c786fcf2df0e02021dc931fe5491981355e5191fd82fb82e3d63003bc555abb41e4501362daeab867",
          "sha256": "c227d88bcdf2913db00df1a80bda65743f3231809355b9a5d33a9f86f61b3977",
          "sha1": "fd5b60047a32ac5efd9d345d74271ff6f0867845",
          "md5": "40bc993733cec55e1d21742054df2438"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.2.8.jar",
          "url": "recipe-0.2.8.jar",
          "size": 51712,
          "sha512": "d617c847c83aa90efd0c3b154d867c281cbfdd1c0072001c786fcf2df0e02021dc931fe5491981355e5191fd82fb82e3d63003bc555abb41e4501362daeab867",
          "sha256": "c227d88bcdf2913db00df1a80bda65743f3231809355b9a5d33a9f86f61b3977",
          "sha1": "fd5b60047a32ac5efd9d345d74271ff6f0867845",
          "md5": "40bc993733cec55e1d21742054df2438"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.8-sources.jar",
          "url": "recipe-0.2.8-sources.jar",
          "size": 8474,
          "sha512": "be57d767af18ffccf0b8ce7645c0cfe08707092da3ba6280d3f4e8fda452946c9e74b1840fc5cbe273747b7d0292058f8022acf0ab26c713ffe664a3a581e939",
          "sha256": "88b1678ff4e7dab7551cc2d071ad442f5280ad24b5cf1958e7bc17edb70c84ae",
          "sha1": "a9c32034152462c64375e7ed45fbfc9c7ab55a8a",
          "md5": "e3f2cbff8c1627f820366176e8d4e984"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.8-javadoc.jar",
          "url": "recipe-0.2.8-javadoc.jar",
          "size": 261,
          "sha512": "aa6b5cb2332848a078a82d21d9be7eb4ea991ab44f556cbe1e5364cd81343dabfaccb88cde5b455e21de767d050583040f1872a34fe4ae8b2e66becb9b55cf7a",
          "sha256": "a949f45f236ebb84c16f9879552df7ccbf2a73358cfc9d5e3bf82028b38ffe62",
          "sha1": "edb451d669d597a8d781c7dc273a8e7504936297",
          "md5": "08bb8e2f6bdf740a180f8108f3167253"
        }
      ]
    }
  ]
}
