{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.2.1.jar",
          "url": "recipe-0.2.1.jar",
          "size": 64627,
          "sha512": "87ee87147f7de9b9d5b6712079c41c1832b803e01158f9024b74e05563d243bd93e82e37b0b01488ee1d359bd0322d5f773966e2d35ef21d98e979eeeb090bf2",
          "sha256": "b4979fe95c4471660daabf75b54acf8b9e83b5bd3ac99e07c5330b7c93a88d2c",
          "sha1": "ae162c12497a0b2af45a08d475aa8c7b26bdba60",
          "md5": "0f3decc9cfefeadfaf2bf905849b0a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.2.1.jar",
          "url": "recipe-0.2.1.jar",
          "size": 64627,
          "sha512": "87ee87147f7de9b9d5b6712079c41c1832b803e01158f9024b74e05563d243bd93e82e37b0b01488ee1d359bd0322d5f773966e2d35ef21d98e979eeeb090bf2",
          "sha256": "b4979fe95c4471660daabf75b54acf8b9e83b5bd3ac99e07c5330b7c93a88d2c",
          "sha1": "ae162c12497a0b2af45a08d475aa8c7b26bdba60",
          "md5": "0f3decc9cfefeadfaf2bf905849b0a01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.1-sources.jar",
          "url": "recipe-0.2.1-sources.jar",
          "size": 8856,
          "sha512": "336733e02a7fc55f32921725f7dae2997ea747d37c2caf6616d1bb6f550f36e6683ccd8a5782e04c710bfdef25e43a3df9df2bd000fd5eb17ecbdd5c00362497",
          "sha256": "2728bda670cabd7affeac88bf529681ea8cd88c54f1c03d0d720a9f2bd34413a",
          "sha1": "e622058ed0d0fc7c9f010226f1f4f149878e1458",
          "md5": "2b46a0eb89d8bf91d2fd25cdb98cf96c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.1-javadoc.jar",
          "url": "recipe-0.2.1-javadoc.jar",
          "size": 261,
          "sha512": "d328def7f539328e20039057793c614cb9e7ac30bf5e94f499ca44a4ad86b753db1100ea0ff347cc1f8d80dc2a487d4c3e33be113a1df3dad68cab6b41ce4d47",
          "sha256": "a4328399f60f2effbd9e14fbe565148a2572ebf9201f35e1f6e5ecbe2f4daace",
          "sha1": "cf4fbc12f75041e814e1207e06204ad6f245900a",
          "md5": "1e9745444b521ede7299fda9c1980bad"
        }
      ]
    }
  ]
}
