{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.1.3.jar",
          "url": "recipe-0.1.3.jar",
          "size": 50998,
          "sha512": "80ebff2044aeaf304096c14a66197077c6c173e5afad4f111417b78daee53503839b35eacf6167a61329448a4c93b2726e1cc43eed649ed78966e68fc987f767",
          "sha256": "dc1859e0ff3a057c054a7c1763c77db74e8bd110a4d0bf96f401e59846a5e5a9",
          "sha1": "f1de23d1dd2366bd53478bb58dfb755453e3de06",
          "md5": "3ea0c34f84aa264e085bd37224f2f062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.1.3.jar",
          "url": "recipe-0.1.3.jar",
          "size": 50998,
          "sha512": "80ebff2044aeaf304096c14a66197077c6c173e5afad4f111417b78daee53503839b35eacf6167a61329448a4c93b2726e1cc43eed649ed78966e68fc987f767",
          "sha256": "dc1859e0ff3a057c054a7c1763c77db74e8bd110a4d0bf96f401e59846a5e5a9",
          "sha1": "f1de23d1dd2366bd53478bb58dfb755453e3de06",
          "md5": "3ea0c34f84aa264e085bd37224f2f062"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.3-sources.jar",
          "url": "recipe-0.1.3-sources.jar",
          "size": 8002,
          "sha512": "0b9b9c7f91813abbd76bf35c5f0add64456ea1edf61ea402beff006d09b9c33b1f5611d13eb0260f0b4008cd476644101b522b662c0f83735e9a2e7b2477d4f0",
          "sha256": "2dc10b59370f05a1a1bcfd5af573cac63b53802529e37ead2cc099aae832f56a",
          "sha1": "0ae88e632ec913167c08577a003fbe6e24378916",
          "md5": "467effbd23722fcc8beed01587892ab6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.3-javadoc.jar",
          "url": "recipe-0.1.3-javadoc.jar",
          "size": 261,
          "sha512": "953037644034b547016d08b706f6e1680397a05443b6b82c35122399f5e6c7a6b0686ee9db6163b93abb71c42fc710e369a912e3f8299693f2cbb77ca7ca9dbc",
          "sha256": "e191e17dbff089da49e1537b424d32ee87b289e32a3591f2a6c6c7b39b804ea4",
          "sha1": "c0395ede918a0c9703d32f59abfdc0f160b63503",
          "md5": "fe8ff034654cf290b48f1d7639987923"
        }
      ]
    }
  ]
}
