{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.1.1.jar",
          "url": "recipe-0.1.1.jar",
          "size": 53341,
          "sha512": "eff0ffdad864ab7c20d1d79392d360551ef4ef648475db345b7015ffab079fc1040b083c459014faa7d7163b1b2640a364c319000944cbc2164571debcbb1166",
          "sha256": "ef19fc2aca01caaa97e5d291de32c1ab170b8e446cab0a6f20bdf53754bfe383",
          "sha1": "22fd2e56792c5fb1ee3ce9d4c2b8f40bf33db635",
          "md5": "326541cc8a9d6981b4ffdde88fa53dc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.1.1.jar",
          "url": "recipe-0.1.1.jar",
          "size": 53341,
          "sha512": "eff0ffdad864ab7c20d1d79392d360551ef4ef648475db345b7015ffab079fc1040b083c459014faa7d7163b1b2640a364c319000944cbc2164571debcbb1166",
          "sha256": "ef19fc2aca01caaa97e5d291de32c1ab170b8e446cab0a6f20bdf53754bfe383",
          "sha1": "22fd2e56792c5fb1ee3ce9d4c2b8f40bf33db635",
          "md5": "326541cc8a9d6981b4ffdde88fa53dc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.1-sources.jar",
          "url": "recipe-0.1.1-sources.jar",
          "size": 7939,
          "sha512": "e08e6393e1e04192d2cbaaa84fe0c00242d364eb8e5c73e93e0c887ef93adb0b682938b6b623226eca8b1c81605a8db17535fb10a6cf1ed1cd6c180120203d18",
          "sha256": "8565baed0d2b9a7f17fe6e841eb2a28a6d30e0ba3acca84d506989046b9f449e",
          "sha1": "422a92fb4ba9d0aa2a0e06903823903cf935242e",
          "md5": "d14d72625582e880be2d9834227bf95f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.1-javadoc.jar",
          "url": "recipe-0.1.1-javadoc.jar",
          "size": 261,
          "sha512": "e7a02b598f0fc20780645f4869e7f26134058d0d786fe19abb31709ec33ff410177f9809ca039ee373c4bcf13692d60c61a05a3f1a5067a4745586ebf105bae2",
          "sha256": "b0032e089ba7b95ef7619b0d0fb1fab5fa0862a4141e2578c9f6a8331e6f625f",
          "sha1": "6f44194e1d5b5e15bf6a387a201a168964805483",
          "md5": "bb6b939101fb48e0d1fda244a4008e9c"
        }
      ]
    }
  ]
}
