{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.0.4.jar",
          "url": "recipe-1.0.4.jar",
          "size": 53289,
          "sha512": "7ba73a431e273811a375f7ade2cbe86ec0f4730f469ffe548f9fd64ef0e946fa85460c15f1a3c2376d500ea54cdf187a3e265197b4cfb4ca1bedc3590eec7e3e",
          "sha256": "03d2a1b84aa2598c33a188321976de5ca1f487b96c4fe74c2df1e9d8591b0a0d",
          "sha1": "7b85f2185a47d181574dc18103a1f5a121045f98",
          "md5": "87de8a83a6d3ce31133dd7feaba82761"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.0.4.jar",
          "url": "recipe-1.0.4.jar",
          "size": 53289,
          "sha512": "7ba73a431e273811a375f7ade2cbe86ec0f4730f469ffe548f9fd64ef0e946fa85460c15f1a3c2376d500ea54cdf187a3e265197b4cfb4ca1bedc3590eec7e3e",
          "sha256": "03d2a1b84aa2598c33a188321976de5ca1f487b96c4fe74c2df1e9d8591b0a0d",
          "sha1": "7b85f2185a47d181574dc18103a1f5a121045f98",
          "md5": "87de8a83a6d3ce31133dd7feaba82761"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.4-sources.jar",
          "url": "recipe-1.0.4-sources.jar",
          "size": 8624,
          "sha512": "4fe7ac703ac3f844d594eab30e496cfa58c626648b020f81b633223cc8260a525f3f830181f2b8fc2fd5053617afa823f57b2e919ea5ddf5be84b83d1c59d239",
          "sha256": "8386b322f7ac9a483006d5d6271d25c82bf322493b18ac83c38ef05fc01aaf92",
          "sha1": "f3fcacf327396dfeb8f926236d79c51700e05522",
          "md5": "3b9734b8eea9a5d2b211ce1cac444f4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.4-javadoc.jar",
          "url": "recipe-1.0.4-javadoc.jar",
          "size": 261,
          "sha512": "5a6a3f54b140d717472de2bc6d3672c4203c9b922c025d77cdad7da37a0484724986490a4177976628732bc7c56026fe46b58227d5fd6daade7af6fad6fe0dfa",
          "sha256": "4ffb2cc34878457096aee20d0abf167a48dbf7b5117222e3ecade9f64930dc8d",
          "sha1": "b32a390e4d8fcf0235e647aa493a417ad8774f2c",
          "md5": "67bd547024245ed5caecaefe338f5cc9"
        }
      ]
    }
  ]
}
