{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.0.5.jar",
          "url": "recipe-1.0.5.jar",
          "size": 55918,
          "sha512": "6f336157a63cc49766127d46924d96b6a989daa09eaa0094ae71599baf96845798d048e40c6f3da5fddbe0d6a8fbb21a146b7510d35f1e9918285d968771781c",
          "sha256": "43fc207b3e5813a5b050b8ad5f973b38b7aa6d417169be6197ebf9b4788da9d7",
          "sha1": "39f4c4b13cbed3f7457c0695b6419483eeee37a6",
          "md5": "a2642fdd8e8380a346c7d07a4f51f7c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.0.5.jar",
          "url": "recipe-1.0.5.jar",
          "size": 55918,
          "sha512": "6f336157a63cc49766127d46924d96b6a989daa09eaa0094ae71599baf96845798d048e40c6f3da5fddbe0d6a8fbb21a146b7510d35f1e9918285d968771781c",
          "sha256": "43fc207b3e5813a5b050b8ad5f973b38b7aa6d417169be6197ebf9b4788da9d7",
          "sha1": "39f4c4b13cbed3f7457c0695b6419483eeee37a6",
          "md5": "a2642fdd8e8380a346c7d07a4f51f7c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.5-sources.jar",
          "url": "recipe-1.0.5-sources.jar",
          "size": 8651,
          "sha512": "1f169bf6d3d70de314c44637d4ac9a1d614720d17f7a2acbf9c45d81483d79dadcfd1788d62cb8ebbb62e6dfa72f741ba43b20cb1211ec63e547ede415a18095",
          "sha256": "4470a0d733c23192e1c2f0de63e3fef67389652f5c9ebfc9452d415d369a2a0e",
          "sha1": "d773da9b8d674a365beafff48a03b870f2a704ea",
          "md5": "43b6256d4e2faa57262e372f40e9b497"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.5-javadoc.jar",
          "url": "recipe-1.0.5-javadoc.jar",
          "size": 261,
          "sha512": "6db43d923695bca068146024137524ed95ab02f681f18bc371289dbc5b9381d34ccd8d4ea52f10c7a7c971ba1cc6faa67775a38dcfcd1d844b511fbbcb698248",
          "sha256": "53c45c8db432eec8bafab4389cfc57c92ae77cd0641b390f0c55dfa46444739a",
          "sha1": "f8480f171f3f40e306aa24790917d673a94eeb4d",
          "md5": "3154d86dd2f26daf6a42828610e9733a"
        }
      ]
    }
  ]
}
