{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.1.0.jar",
          "url": "recipe-0.1.0.jar",
          "size": 52986,
          "sha512": "8f0b21d7ccb279db286e4f68ad47b322120b88d43d0691c73fb417adc4be5e940cda478643f49f21c83b263a70be7abbae14bc59c303b07e49a4ef4bf87307e6",
          "sha256": "10c0e2fff3c9c6f223af4a0600ebcef3fe8c3400608584df8b42d2f331eefea0",
          "sha1": "97ff549190df156a8e60972ced0c66abfa111dff",
          "md5": "cdc15f70dd0f3fcf03876c5c146f9659"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.1.0.jar",
          "url": "recipe-0.1.0.jar",
          "size": 52986,
          "sha512": "8f0b21d7ccb279db286e4f68ad47b322120b88d43d0691c73fb417adc4be5e940cda478643f49f21c83b263a70be7abbae14bc59c303b07e49a4ef4bf87307e6",
          "sha256": "10c0e2fff3c9c6f223af4a0600ebcef3fe8c3400608584df8b42d2f331eefea0",
          "sha1": "97ff549190df156a8e60972ced0c66abfa111dff",
          "md5": "cdc15f70dd0f3fcf03876c5c146f9659"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.0-sources.jar",
          "url": "recipe-0.1.0-sources.jar",
          "size": 7019,
          "sha512": "151ebc57c7307ad9c1534f600c385553209af177fde9b2e617e2ad3793d15496927880b52cb91c1b577c71df22f3920832e0f8dd574c1b37fdddebfebab1bb81",
          "sha256": "c554878bbcb1142541f037a33302f15feee2d44ce983117f59acadb58cc9771d",
          "sha1": "df21e5ab3864faee9bb59ebacd4cf774fce6ebd7",
          "md5": "f19f83de21c3c1312a9d332fabe288dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.0-javadoc.jar",
          "url": "recipe-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "ae4ac42628dbd73eba2e6d3d8ce1ee4bdf83389b5ea1f98f6b4b8f0a24b8167004a1e1e940ee281ba68f1a6360a0a9f0ca90caec3062a39328c2585eedde555d",
          "sha256": "4b1c62413184ffeac366f634ed91c8d31b844c857c104f71e8f2612ba4fcc9c7",
          "sha1": "004f80ec3a810b29aa76972c3155c2e866b67919",
          "md5": "bcd17a8b2109de3a5473a01675f92a40"
        }
      ]
    }
  ]
}
