{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.0.0.jar",
          "url": "recipe-1.0.0.jar",
          "size": 51710,
          "sha512": "badba2d608ef3fdd6f874e5178a6b3b76afc7c9b4c1f60a62e5550945b34237a0182a3feca000f4a94efbc915e7f03992d30f3cffbc58fccd584b37b822f2774",
          "sha256": "e6ccb4949431f4e4744bed9551bbc8c5cd78d8445eda9e5f35f071291f504483",
          "sha1": "8032e7b3af313c51d71d7e3605cd065eec7e2fb3",
          "md5": "798f80c54e0f1c8a8fa00bf6545f8f1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.0.0.jar",
          "url": "recipe-1.0.0.jar",
          "size": 51710,
          "sha512": "badba2d608ef3fdd6f874e5178a6b3b76afc7c9b4c1f60a62e5550945b34237a0182a3feca000f4a94efbc915e7f03992d30f3cffbc58fccd584b37b822f2774",
          "sha256": "e6ccb4949431f4e4744bed9551bbc8c5cd78d8445eda9e5f35f071291f504483",
          "sha1": "8032e7b3af313c51d71d7e3605cd065eec7e2fb3",
          "md5": "798f80c54e0f1c8a8fa00bf6545f8f1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.0-sources.jar",
          "url": "recipe-1.0.0-sources.jar",
          "size": 8473,
          "sha512": "767aa0861d47c0f69900c951dc8b65f1ebf3edf3597f5ef0f6060a76304b36bcbc33d29276cab7e777436d3635cefdc939af4940f2acaa5fec83ae324294b461",
          "sha256": "8c44f73c639766bfa4613af86bb27c8d24504706f035c0f58f173ba2675fb290",
          "sha1": "4ec05b2e3410dee13f86fc2bcac1a0643f2c388f",
          "md5": "d1a01f3cec1a85bcadac3c598910f571"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.0-javadoc.jar",
          "url": "recipe-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "94aae0bb1e2479f904b2838e7edd23ee70e914d8e88d96982ee8594b0c86238e9413454bddb61f80b7a58c4ed10bf54460e459ee54cdba45698c7b44ffc2945f",
          "sha256": "5b39d59e91e7c1c4fcaa4627309cf9256677a4965c6b6a83c23059918008afd7",
          "sha1": "e9bc91ce5fad6e1361cae635da0c4ae57bf04dad",
          "md5": "bf3050320f1f73bae4492cb8c98057f9"
        }
      ]
    }
  ]
}
