{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.2.0.jar",
          "url": "recipe-1.2.0.jar",
          "size": 35484,
          "sha512": "a7d61f8aaa388e6825bf6121f6fe32804b37910112efa2cb148084bda183a78ee114a19b9020a4f814947873370d234b9143373307c47523fa83f6e6744490bd",
          "sha256": "6f96c4bdc332f95199fb66b2051adcaad088e531e4a3c72d355fb8b197f9312d",
          "sha1": "d0e31f41effbeed2173715e8e494f41a00022eac",
          "md5": "0c5576892efaa471a94c56dc27e6ca9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.2.0.jar",
          "url": "recipe-1.2.0.jar",
          "size": 35484,
          "sha512": "a7d61f8aaa388e6825bf6121f6fe32804b37910112efa2cb148084bda183a78ee114a19b9020a4f814947873370d234b9143373307c47523fa83f6e6744490bd",
          "sha256": "6f96c4bdc332f95199fb66b2051adcaad088e531e4a3c72d355fb8b197f9312d",
          "sha1": "d0e31f41effbeed2173715e8e494f41a00022eac",
          "md5": "0c5576892efaa471a94c56dc27e6ca9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.0-sources.jar",
          "url": "recipe-1.2.0-sources.jar",
          "size": 8649,
          "sha512": "098b4e0128dda6c7d5714311cdfa5b23240da54729031d7bda5091c6d5afcadc72a98fbfd4e38e7dc577fc7117a28ea96161d65b6539164321dddbc7452e79bd",
          "sha256": "9422d416982d5c46b436eb34156c93d4221e42e0fded7a6dc073c5055b4df2b7",
          "sha1": "5bd607dd8e4ec5561e80d4dd8cc303d22d933fa2",
          "md5": "157e409abbe130be84e7554d16cff9a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.0-javadoc.jar",
          "url": "recipe-1.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
