{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.0.3.jar",
          "url": "recipe-1.0.3.jar",
          "size": 53288,
          "sha512": "0efa814999680cdd20e1da72d6842153c472a1ca43fbcc10c34a4790ab64f6ad2a9a0bbc793295023536d4aafbf448ccad40fae0beaf762bbbca0823feaa2c45",
          "sha256": "ef00dd939970046e94f75e197f4ca18623d4f32479c2416a6dc9e95d391bbe61",
          "sha1": "581dfcbb58610dc03178203933244f99f58d6826",
          "md5": "f4afb9e0e945b09ccfee54d17205aa95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.0.3.jar",
          "url": "recipe-1.0.3.jar",
          "size": 53288,
          "sha512": "0efa814999680cdd20e1da72d6842153c472a1ca43fbcc10c34a4790ab64f6ad2a9a0bbc793295023536d4aafbf448ccad40fae0beaf762bbbca0823feaa2c45",
          "sha256": "ef00dd939970046e94f75e197f4ca18623d4f32479c2416a6dc9e95d391bbe61",
          "sha1": "581dfcbb58610dc03178203933244f99f58d6826",
          "md5": "f4afb9e0e945b09ccfee54d17205aa95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.3-sources.jar",
          "url": "recipe-1.0.3-sources.jar",
          "size": 8623,
          "sha512": "5464f9a82e3ada16b503c4b7164d8f75ed85df3a9b0355664a049be96d5be105c7d6b12dcc5374b9fa57abbfe71de7e59b0d03cf808fa1f4d3b5de409e6f3523",
          "sha256": "60eed36e0c184f05b21e92a40c1203c881312c8ca26fb8578524c49314f9290c",
          "sha1": "6cbb251e3fcef3588dacd3e9f4b0776703c0e072",
          "md5": "e2e823cf173356b65ffe93febda67cea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.0.3-javadoc.jar",
          "url": "recipe-1.0.3-javadoc.jar",
          "size": 261,
          "sha512": "1acb513689bf1d36db3198c0baf02b21edf45d8fd4d28cba2daea14aea8189c3eedd2836f3662fc8d2af560c29eee24d9a3498f62db157e22861354e871da06e",
          "sha256": "3cfa800fa37afb050897cb268dc027d3f970742839e0b0782bf077254ed72ade",
          "sha1": "21c691d34cabd7eb368f37aefe26f38af0a66518",
          "md5": "227152ba9e1eef187e46417cd2411dde"
        }
      ]
    }
  ]
}
