{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.1.4.jar",
          "url": "recipe-0.1.4.jar",
          "size": 51222,
          "sha512": "8aec5e643cb059077252b30d9c6aa72b5d8affc2a6b089f82aa07090750ad0d461b2999a1f9eed3103bc5ae4e0da24e8b2cd38f9194ed0e0df93f83661ac64c3",
          "sha256": "6565838b839780aaeba54fb30c5d2a5f7da5a3328367aafc6727a235599821db",
          "sha1": "c1aff8df19f2df0848780a22a4eba37d3cac8996",
          "md5": "db2dfba1df829b20b3a823ff0629ed96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.1.4.jar",
          "url": "recipe-0.1.4.jar",
          "size": 51222,
          "sha512": "8aec5e643cb059077252b30d9c6aa72b5d8affc2a6b089f82aa07090750ad0d461b2999a1f9eed3103bc5ae4e0da24e8b2cd38f9194ed0e0df93f83661ac64c3",
          "sha256": "6565838b839780aaeba54fb30c5d2a5f7da5a3328367aafc6727a235599821db",
          "sha1": "c1aff8df19f2df0848780a22a4eba37d3cac8996",
          "md5": "db2dfba1df829b20b3a823ff0629ed96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.4-sources.jar",
          "url": "recipe-0.1.4-sources.jar",
          "size": 7999,
          "sha512": "db35d633a3c801c95b747cdb09c886e9ad8fc4898796aeae9f85a0c49ad26c26b45b676565250daae1a5c1381e873f62918209ab3eb7336666be4adb18cf0935",
          "sha256": "e5bc81e5ed0ac09867769123cc9c637871ff0b3b80fb45f7f719292552156ad0",
          "sha1": "25ba2b841cb4c9661537adb10dc4cbf4edf65d58",
          "md5": "430e1bdff6b7f38b822d36ee152848d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.4-javadoc.jar",
          "url": "recipe-0.1.4-javadoc.jar",
          "size": 261,
          "sha512": "43f60b30dea286e4e54a1b65a1539f720aa4081a1d4ed4f0a96e968a670ce5a7338e072233749798f1ae41546862ab141673b0c97e6490ca793ab704d8a46272",
          "sha256": "9c5d7f99b5c9c30e286d43b0f859bca7a5a88cec9670f00d89c705b5707d958f",
          "sha1": "a464d65c22fe7233b6a12298b53c1797300d4e85",
          "md5": "414c5565efc188a936386f3a1ed2522d"
        }
      ]
    }
  ]
}
