{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.2.2.jar",
          "url": "recipe-1.2.2.jar",
          "size": 35445,
          "sha512": "1efe8eab4d9fb589a625a4eea264253afa0c2af05762309be5ad7153b5add9f7e0af9eaddd3cc1a7d05cfc9a2b8642e5421c6f3c8a901cd4333ebabb8c998d64",
          "sha256": "cf9a2dcec5d7e4f7cc078af67d1d07ad800e36d29c44fb8217dfcfc97323e663",
          "sha1": "d58e45ad97bd907c50102ce252bc6055976fa5f3",
          "md5": "62876642bd2fa8c069413d88c57acf96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.2.2.jar",
          "url": "recipe-1.2.2.jar",
          "size": 35445,
          "sha512": "1efe8eab4d9fb589a625a4eea264253afa0c2af05762309be5ad7153b5add9f7e0af9eaddd3cc1a7d05cfc9a2b8642e5421c6f3c8a901cd4333ebabb8c998d64",
          "sha256": "cf9a2dcec5d7e4f7cc078af67d1d07ad800e36d29c44fb8217dfcfc97323e663",
          "sha1": "d58e45ad97bd907c50102ce252bc6055976fa5f3",
          "md5": "62876642bd2fa8c069413d88c57acf96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.2-sources.jar",
          "url": "recipe-1.2.2-sources.jar",
          "size": 8613,
          "sha512": "1cf393af28b98472d19c88709c8d1ba80343249cbb49469462446c7f62c6564d7cf263e368f37e2a0642adc5022c65417b7bfb1a4ac8fa9c7318917d06c2e10c",
          "sha256": "1cd80dfffe61245216e377a18c2ccac897c38bb57611db97d0dbaed779bc6228",
          "sha1": "68d95ec09c55a583cff581498f89fa4f5977e077",
          "md5": "c56bd14c257332fb90ab094297db07d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.2-javadoc.jar",
          "url": "recipe-1.2.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
