{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-1.2.1.jar",
          "url": "recipe-1.2.1.jar",
          "size": 35445,
          "sha512": "ffa1732f89c826e62b675cc8de1f4da4bde3c5f0d0e302a6daf29f8cb47a2631f05b2bbef2645a81e9dc24d2d0d9b001a7abc161e8d3531f35ad6d2cd34ed262",
          "sha256": "aedb14489901b5819db75a51b5359b1ffb90207c810bcc258123224d94831468",
          "sha1": "f8e8e14fad8795aa619de7dbef17ab00b31a19c8",
          "md5": "936151f1a1b0faecf37b05c37e4acc03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-1.2.1.jar",
          "url": "recipe-1.2.1.jar",
          "size": 35445,
          "sha512": "ffa1732f89c826e62b675cc8de1f4da4bde3c5f0d0e302a6daf29f8cb47a2631f05b2bbef2645a81e9dc24d2d0d9b001a7abc161e8d3531f35ad6d2cd34ed262",
          "sha256": "aedb14489901b5819db75a51b5359b1ffb90207c810bcc258123224d94831468",
          "sha1": "f8e8e14fad8795aa619de7dbef17ab00b31a19c8",
          "md5": "936151f1a1b0faecf37b05c37e4acc03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.1-sources.jar",
          "url": "recipe-1.2.1-sources.jar",
          "size": 8614,
          "sha512": "71e543be35127232320cfcaa9197f3904c4c6732e3583748cd4040426ae3acde8768906b34cee6d2b5e74deb0719eacdbbc352f244b25851ec4e040f790b5f90",
          "sha256": "f731bf2f50791802d05488ada58bd8964019b5e148d4b3f4d35f08445cbd3d79",
          "sha1": "b09f8d88280fc692979e3dfe21571855b98d1821",
          "md5": "a0f23195be65a60dcbc04cf0647b8b4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-1.2.1-javadoc.jar",
          "url": "recipe-1.2.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
