{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.2.2.jar",
          "url": "recipe-0.2.2.jar",
          "size": 64624,
          "sha512": "06ce93a765d5324a19311a2fae0886711c8b83cec2061c21f97e95177dcb936b9fb53a1f733a1932fdc0ad568ae2ce1679f23a984cfab1ab08420f3205e11da6",
          "sha256": "4fc274d225633109e29fed569453bdf47204627271a1e474f6c4cbc328a9a576",
          "sha1": "9d30d435e234cb906c1f6f3b1c9ebde5bc291572",
          "md5": "082d9aa5d81917bba6e044db7343ea47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.2.2.jar",
          "url": "recipe-0.2.2.jar",
          "size": 64624,
          "sha512": "06ce93a765d5324a19311a2fae0886711c8b83cec2061c21f97e95177dcb936b9fb53a1f733a1932fdc0ad568ae2ce1679f23a984cfab1ab08420f3205e11da6",
          "sha256": "4fc274d225633109e29fed569453bdf47204627271a1e474f6c4cbc328a9a576",
          "sha1": "9d30d435e234cb906c1f6f3b1c9ebde5bc291572",
          "md5": "082d9aa5d81917bba6e044db7343ea47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.2-sources.jar",
          "url": "recipe-0.2.2-sources.jar",
          "size": 8852,
          "sha512": "a2adb831390087e1f0b268d6685dcd3d399f1e1c666407a9f82dbfbee3d1e3bbedf8f26e46bd4f1e06a086f051aea60cad4101ade0c5490ee016a72091fabfb8",
          "sha256": "3bf0c1a2dba02c36d509c7b5a8ff32e63642473e5a6c96ae382ae5f93c0f483b",
          "sha1": "fceba59c5d3001aac63b8009de33a842fe5919fa",
          "md5": "c8a035a8521300799639c36473a84551"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.2-javadoc.jar",
          "url": "recipe-0.2.2-javadoc.jar",
          "size": 261,
          "sha512": "0b97c21b0f6dc1b39fc6659d8ee1cc354b4b32bee0440d4ceea19b08d162bf86747e1956e4dc189ecb41e34579cd432dc606e03cbe871cbcba886a9afdcb8ea0",
          "sha256": "95023b35938c73020d9cf7be81638ab2ce7bf5712640e018e789ce6ec7422fab",
          "sha1": "70b3f5fd7c19835e632c2571ac9e27204c1f36a9",
          "md5": "0cd27011ae26350197dfad67697c85de"
        }
      ]
    }
  ]
}
