{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.1.2.jar",
          "url": "recipe-0.1.2.jar",
          "size": 50823,
          "sha512": "891b88f079727fb644d3fd55680537175fdab825c084e0deeb26f3b3c2de12d6eb3b91237425ae2cc479596c8646eaa60a07217e8fda1353b27b53148bd55646",
          "sha256": "68a7fdbd77ae80685cfbb2c978818bc16c2a649612991a5a977c7f65f7132815",
          "sha1": "551df385d14eff579cd5bdf3fcf19513185d7b6f",
          "md5": "9a9d80ead6c964232633cf239dba5a2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.1.2.jar",
          "url": "recipe-0.1.2.jar",
          "size": 50823,
          "sha512": "891b88f079727fb644d3fd55680537175fdab825c084e0deeb26f3b3c2de12d6eb3b91237425ae2cc479596c8646eaa60a07217e8fda1353b27b53148bd55646",
          "sha256": "68a7fdbd77ae80685cfbb2c978818bc16c2a649612991a5a977c7f65f7132815",
          "sha1": "551df385d14eff579cd5bdf3fcf19513185d7b6f",
          "md5": "9a9d80ead6c964232633cf239dba5a2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.2-sources.jar",
          "url": "recipe-0.1.2-sources.jar",
          "size": 7966,
          "sha512": "4a1eb3f0a5c0f764396c29666dfa6633463747186649d94855f5968b855b34932a15aa5aeca4517060528a153d37e4c2a9020f8bc12816b8b48f282c5588404f",
          "sha256": "15a1170f5cfc52428ffb1b3ffd3abcf2005cc335ebb30f47d77926b96474340f",
          "sha1": "68f914e3c3eb5443a3ddd92436123a77edd5c520",
          "md5": "1d96c59ddd37386ece27b3baabb894f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.1.2-javadoc.jar",
          "url": "recipe-0.1.2-javadoc.jar",
          "size": 261,
          "sha512": "3fb2b6e80c41d1c48e7fa9848ed198776d6808a092cc20b5570b0c28c55ff65cf94d2fc9f520da6992ca7c62bd0983692ee2da1a6c2cae0d3253300f1f89301a",
          "sha256": "98194789c78f8bb3e9619509d2ff0961312b31f02f991597782f7a6f0b8809f0",
          "sha1": "e09d23c28d36e417a03a22334a3e09ea4655249f",
          "md5": "f4a891cab4000629ad4f88198879d5c1"
        }
      ]
    }
  ]
}
