{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "recipe",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "recipe-0.2.5.jar",
          "url": "recipe-0.2.5.jar",
          "size": 58071,
          "sha512": "b5525c590bfb830c28b5451c039038182f01c6b43c863fb576403ce0ffc408065c8c602c4d3499517f2ac52bae7d4bbb8df70b041b1bd480019c201a1d936dfc",
          "sha256": "15bb33fb0d45c66678696ea64bed26562bef303de2057fb220787bac31c0d797",
          "sha1": "29ea24c19ab1b4e0ab9bdd620bd7b2cb8617ff22",
          "md5": "1e3b6e941ab474002486ad715424d6c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "recipe-0.2.5.jar",
          "url": "recipe-0.2.5.jar",
          "size": 58071,
          "sha512": "b5525c590bfb830c28b5451c039038182f01c6b43c863fb576403ce0ffc408065c8c602c4d3499517f2ac52bae7d4bbb8df70b041b1bd480019c201a1d936dfc",
          "sha256": "15bb33fb0d45c66678696ea64bed26562bef303de2057fb220787bac31c0d797",
          "sha1": "29ea24c19ab1b4e0ab9bdd620bd7b2cb8617ff22",
          "md5": "1e3b6e941ab474002486ad715424d6c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.5-sources.jar",
          "url": "recipe-0.2.5-sources.jar",
          "size": 8865,
          "sha512": "37f9b922dd6400918c18c63276cdf0eecbbd30ffbc933c351ecab1894b0e176e3fd32d70c6f097f36453a52a71b6393855cf9cf5fa1838d943926286ec3f8716",
          "sha256": "a20d3dcd20dd038d3835228b99e6f372bbcc745bea5e42bb70a93a94b8d96539",
          "sha1": "911250df4cfb811343ec83550f8a7dd700c19937",
          "md5": "7ed5e08c9e91180043f9fb59c7085d89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe-0.2.5-javadoc.jar",
          "url": "recipe-0.2.5-javadoc.jar",
          "size": 261,
          "sha512": "947ebbf73df5d1c0be86a916f2a310c6867d148bffdc2d3ed4de010ebb8579b5c056ced2a47f9d2663ad5c8ae0a31f3f0c7e9acaf493ae545166343c023b3858",
          "sha256": "3ba1b9055d61f682bc0bf6603dda2e5ec48b912a73c6d83fc4364c7e228692c7",
          "sha1": "d1bc713f448c183bc037e1f1d7268548057ac7b7",
          "md5": "7959e8f08d2b1fe6180ee58e6ab2457b"
        }
      ]
    }
  ]
}
